edit-README.md
orangina92/chatspace pull request #1
Opened 2019-02-27 12:13 UTC by orangina92

edit-README.mdにデータベース設計を記述しました

2019-02-27 12:17 UTC, yuki-uchida requested changes

2019-02-27 12:17 UTC, yuki-uchida commented on chatspace/README.md
> +|group_id|integer|null: false, foreign_key: true|
外部キーを使用する場合にはrefferenceと書きましょう

2019-02-27 12:24 UTC, orangina92 commented on chatspace/README.md
> +|group_id|integer|null: false, foreign_key: true|
ありがとうございます。refference調べてみます。

2019-03-01 03:30 UTC, orangina92 commented on chatspace/README.md
> +|group_id|integer|null: false, foreign_key: true|
|Column|Type|Options|
|------|----|-------|
|user_id|integer|references  :user, null: false, foreign_key: true|
|group_id|integer|references  :groop, null: false, foreign_key: true|

このように記述しましたが正しいでしょうか？

2019-03-01 08:02 UTC, yuki-uchida commented on chatspace/README.md
> +|group_id|integer|null: false, foreign_key: true|
Typeをreferencesにしていただけると良いです！integerでもあってるのですが、外部キーであることをわかりやすくする為です

2019-03-01 08:05 UTC, orangina92 commented on chatspace/README.md
> +|group_id|integer|null: false, foreign_key: true|
ありがとうございます！修正します

2019-03-01 08:14 UTC, merged