add-automatic-updates
orangina92/chatspace pull request #13
Opened 2019-03-08 12:46 UTC by orangina92

チャット画面の自動更新機能の実装しました

2019-03-08 12:54 UTC, TOMARUMARU commented on chatspace/app/assets/javascripts/messages.js
> +    <div class="upper-message">
8~21行目は何故インデント崩しちゃったのでしょう？

2019-03-08 12:58 UTC, orangina92 commented on chatspace/app/assets/javascripts/messages.js
> +    <div class="upper-message">
sublime textの自動整形機能使ったらこうなりました。
戻します！

2019-03-09 01:59 UTC, yuki-uchida requested changes

2019-03-09 01:59 UTC, yuki-uchida commented on chatspace/app/assets/javascripts/messages.js
> +      .done(function(json) {
jsonでは抽象的すぎるので、具体的な名前にしましょう。
何を受け取っているのかがわかるような名前だとよいです

2019-03-09 01:59 UTC, yuki-uchida commented on chatspace/app/assets/javascripts/messages.js
> +            insertHTML += buildHTML(message);
buildHTMLでは、何をどうするのかがわかりづらいので、buildSendMessageHTMLとかいかがでしょうか

2019-03-09 05:23 UTC, orangina92 commented on chatspace/app/assets/javascripts/messages.js
> +      .done(function(json) {
変更しました

2019-03-09 05:23 UTC, orangina92 commented on chatspace/app/assets/javascripts/messages.js
> +            insertHTML += buildHTML(message);
変更しました

2019-03-09 05:27 UTC, yuki-uchida requested changes

2019-03-09 05:27 UTC, yuki-uchida commented on chatspace/app/assets/javascripts/messages.js
> +      .done(function(SendMessageData) {
Dataという単語は外して良いです。プログラムにおいては全てがDataに当てはまってしまいます。
ゾウという生き物に対してelephantAnimalという名前が付いているようなものです

2019-03-09 05:27 UTC, yuki-uchida commented on chatspace/app/assets/javascripts/messages.js
> +        json.messages.forEach(function(message) {
このコード、多分ですけど動いてないですよね？
jsonっていうものが存在しないように思います

2019-03-09 05:48 UTC, orangina92 commented on chatspace/app/assets/javascripts/messages.js
> +      .done(function(SendMessageData) {
修正しました

2019-03-09 05:51 UTC, orangina92 commented on chatspace/app/assets/javascripts/messages.js
> +        json.messages.forEach(function(message) {
修正しました

2019-03-09 05:56 UTC, b-i-hide commented
自動更新をしているところをgifかなんかで確認したいので、貼ってもらえますか〜？？

2019-03-09 06:06 UTC, orangina92 commented
分かりました

2019-03-09 06:06 UTC, orangina92 commented
https://gyazo.com/1a5752b1c863149676b3a496b18a06d6

2019-03-09 06:07 UTC, orangina92 commented
https://i.gyazo.com/1a5752b1c863149676b3a496b18a06d6.gif

2019-03-09 06:14 UTC, b-i-hide commented
これ結局自動更新は失敗してます？

2019-03-09 06:19 UTC, orangina92 commented
https://i.gyazo.com/b3b2a0fde56ab17d108335e7b4f9f2d9.gif

2019-03-09 06:21 UTC, orangina92 commented
ターミナルの動きを見ると自動更新できていると思うんですがどうなんでしょうか？
正しく実装できている場合、自動更新に失敗しましたというアラートは出ないんでしょうか？

2019-03-09 06:26 UTC, b-i-hide commented on chatspace/app/assets/javascripts/messages.js
> +        alert('自動更新に失敗しました');
ここに飛んできているってことですよね？
それは自動更新の機能として正しい挙動ですか？
更新されているのに失敗しましたと表示するのはユーザーの混乱を招くものだと思いますが、

2019-03-09 06:35 UTC, orangina92 commented on chatspace/app/assets/javascripts/messages.js
> +        alert('自動更新に失敗しました');
そうですね、'自動更新に失敗しました'というアラートはユーザーの混乱を招くものだと思い、削除しました

2019-03-09 07:15 UTC, yuki-uchida commented
ajanによる非同期通信が成功した場合にはdoneに、失敗した場合にはfailに飛びます

今回はfailに飛んでいるのですよね？
それはつまり非同期通信が出来ていないということです。まずは非同期通信が動作するようにしなければいけません

何故非同期通信を実装したのかを考えましょう。非同期通信によって何かを実現させたかったはずです。それは今のコードで実現できているでしょうか？

2019-03-09 07:15 UTC, yuki-uchida commented
非同期通信がどうしても上手く動作しない場合には、コネクトでご質問頂ければスムーズに解決することが可能です。宜しければご利用ください

2019-03-09 07:29 UTC, orangina92 commented
分かりました。ありがとうございます。

2019-03-10 10:17 UTC, orangina92 commented
https://i.gyazo.com/8e2daa207aa22d398d87f98702779e93.gif

2019-03-10 10:18 UTC, orangina92 commented
非同期通信修正して実装しました。

2019-03-10 10:46 UTC, hiroki5123 commented
いただいたgifでは自動更新が確認できなかったので、二つのブラウザを開いて片方でメッセージを送信して自動更新されるところを撮っていただいてもいいでしょうか？

2019-03-10 10:57 UTC, orangina92 commented
https://i.gyazo.com/c2a3ecbc230913778d3b6b698aa82df5.gif

2019-03-10 10:57 UTC, orangina92 commented
撮り直しました

2019-03-10 11:01 UTC, yuki-uchida requested changes

2019-03-10 11:01 UTC, yuki-uchida commented on chatspace/app/assets/javascripts/messages.js
> +      var html = buildSendMessageHTML(sendMessageData);
Dataという単語は外して良いです。プログラムにおいては全てがDataに当てはまってしまいます。
ゾウという生き物に対してelephantAnimalという名前が付いているようなものです

2019-03-10 11:01 UTC, yuki-uchida commented on chatspace/app/assets/javascripts/messages.js
> +  function update(){
updateはなにをupdateするのかわかる名前で。

2019-03-10 11:08 UTC, orangina92 commented on chatspace/app/assets/javascripts/messages.js
> +      var html = buildSendMessageHTML(sendMessageData);
修正しました

2019-03-10 11:08 UTC, orangina92 commented on chatspace/app/assets/javascripts/messages.js
> +  function update(){
修正しました

2019-03-10 11:13 UTC, yuki-uchida approved these changes
LGTMです。お疲れ様でした

2019-03-10 11:18 UTC, orangina92 commented
ありがとうございます！

2019-03-10 14:44 UTC, merged